# ------ root_path ------
root_path: '/home/SS/datasets/CaFo_data/DATA/'


# ------ Load Cache and Features ------
load_pre_clipn: True
load_cache: False

# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [7, 3]
search_step: [200, 20]

alpha: 0.3
beta: 0.3
gamma: 0.5
threshold: 0.5

gpt3_prompt_file: './gpt_file/oxford_pets_prompt.json'

# ------ Basic Config ------
dataset: 'oxford_pets'
shots: 1
clip_backbone: 'RN50'
clipn_backbone: 'ViT-B-16'
num_classes: 37
positive_num: 1
negative_num: 10
anchor_num_per_class: 2

# ------ Dalle Dataset -----
dalle_dataset: 'dalle_pets'
dalle_shots: 8

lr: 0.001
augment_epoch: 1
train_epoch: 70

# ------ Open World ------
openset: 'openset'
open_world: 
  is_open_world: True  # True or False
  clean_dataset: False # True or False
  nlb: 1.0 # noise label
  # ds: 0.0 # domain shift
  ood: 0.0 # out of distribution